apiVersion: v1
kind: Service
metadata:
  name: mechanicsdatausvc
  labels:
    app: mechanicsdatausvc
    tier: data-usvc
spec:
  selector:
    app: mechanicsdatausvc
  type: NodePort
  ports:
  - port: 80
